# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/BILLYH2/Downloads/lab7_1_provided_fa24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_cock/mb_cock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock || ORIG_REF_NAME==mb_cock} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_microblaze_0_1/mb_cock_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_microblaze_0_1 || ORIG_REF_NAME==mb_cock_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_dlmb_v10_1/mb_cock_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_dlmb_v10_1 || ORIG_REF_NAME==mb_cock_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_ilmb_v10_1/mb_cock_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_ilmb_v10_1 || ORIG_REF_NAME==mb_cock_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_dlmb_bram_if_cntlr_1/mb_cock_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_cock_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_ilmb_bram_if_cntlr_1/mb_cock_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_cock_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_lmb_bram_1/mb_cock_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_lmb_bram_1 || ORIG_REF_NAME==mb_cock_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_xbar_0/mb_cock_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_xbar_0 || ORIG_REF_NAME==mb_cock_xbar_0} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_microblaze_0_axi_periph_0/mb_cock_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_cock_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_microblaze_0_axi_intc_0/mb_cock_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_cock_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_microblaze_0_xlconcat_0/mb_cock_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_cock_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_mdm_1_1/mb_cock_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_mdm_1_1 || ORIG_REF_NAME==mb_cock_mdm_1_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_clk_wiz_1_1/mb_cock_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_clk_wiz_1_1 || ORIG_REF_NAME==mb_cock_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_rst_clk_wiz_1_100M_1/mb_cock_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_cock_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_axi_uartlite_0_0/mb_cock_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_axi_uartlite_0_0 || ORIG_REF_NAME==mb_cock_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_cock/ip/mb_cock_hdmi_text_controller_0_0/mb_cock_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_cock_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_cock_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_cock/mb_cock_ooc.xdc
