# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/ECE385/lab_7.1/lab_7.1.srcs/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0.xci
# IP: The module: 'mb_block_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: U:/ECE385/lab_7.1/lab_7.1.srcs/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0.xci
# IP: The module: 'mb_block_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_block/ip/mb_block_clk_wiz_0_0/mb_block_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
