# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/ECE385/lab_7.1/lab_7.1.srcs/sources_1/bd/mb_cock/ip/mb_cock_lmb_bram_1/mb_cock_lmb_bram_1.xci
# IP: The module: 'mb_cock_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_cock/ip/mb_cock_lmb_bram_1/mb_cock_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_cock_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: u:/ECE385/lab_7.1/lab_7.1.srcs/sources_1/bd/mb_cock/ip/mb_cock_lmb_bram_1/mb_cock_lmb_bram_1.xci
# IP: The module: 'mb_cock_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/ECE385/lab_7.1/lab_7.1.gen/sources_1/bd/mb_cock/ip/mb_cock_lmb_bram_1/mb_cock_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_cock_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
