# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Warre/fireboy_watergirl_final_project/fireboy_watergirl_final_project.srcs/sources_1/ip/boy_rom/boy_rom.xci
# IP: The module: 'boy_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Warre/fireboy_watergirl_final_project/fireboy_watergirl_final_project.gen/sources_1/ip/boy_rom/boy_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boy_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Warre/fireboy_watergirl_final_project/fireboy_watergirl_final_project.srcs/sources_1/ip/boy_rom/boy_rom.xci
# IP: The module: 'boy_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Warre/fireboy_watergirl_final_project/fireboy_watergirl_final_project.gen/sources_1/ip/boy_rom/boy_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boy_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
